# -*- mode: ruby -*-
# vi: set ft=ruby :

# STAGING

# smarter way to do multi-machine is here : https://manski.net/articles/vagrant/multi-machine-tutorial

Vagrant.configure("2") do |config|

  # All my TRADR application code is on here - node subject to lots of change
  # This is the node the user interacts with - the 'iceberg' terminal
  # Docker, Jython etc.
  config.vm.define "itg_iceberg" do |iceberg|
    iceberg.vm.box = "tradr7"
  #  # tradr0.vm.box_check_update = true
    iceberg.vm.hostname = "itg-iceberg"
    iceberg.vm.network :public_network, ip: "192.168.1.190", bridge: "eth0"
    #tradr0.vm.network "forwarded_port", guest: 3000, host: 7000, host_ip: "127.0.0.1"  # Grafana
    #tradr0.vm.network "forwarded_port", guest: 80, host: 7080, host_ip: "127.0.0.1"    # Web Front-end
    iceberg.vm.provider "virtualbox" do |vb0|
        vb0.gui = true
        vb0.memory = "4096"
    end
      iceberg.vm.provision "file", source: "start_admin_cli.sh", destination: "start_admin_cli.sh"
      iceberg.vm.provision "file", source: "start_stocks_scanner.sh", destination: "start_stocks_scanner.sh"
      iceberg.vm.provision "file", source: "disable-firewall.sh", destination: "disable-firewall.sh"
      iceberg.vm.provision "shell", path:  "./disable-firewall.sh"
      iceberg.vm.provision "shell", env: {
                                        'VONAGE_API_SECRET' => ENV['VONAGE_API_SECRET'],
                                        'VONAGE_API_KEY' => ENV['VONAGE_API_KEY'],
                                        'FMP_FREE_API_KEY' => ENV[ 'FMP_FREE_API_KEY'],
                                        'PROTONMAIL_PLUS_BRIDGE_KEY' => ENV['PROTONMAIL_PLUS_BRIDGE_KEY'],
                                        'ALPHAVANTAGE_BASIC_API_KEY' => ENV['ALPHAVANTAGE_BASIC_API_KEY'],
                                        'ALPHAVANTAGE_FREE_API_KEY' => ENV['ALPHAVANTAGE_FREE_API_KEY']
                                         },
                                         path: './setup-profile.sh'
  end
end
