version: '3'

# Run REST services first
services:

  tradr-all-stocks-stage-classifier:
    container_name: tradr-all-stocks-stage-classifier
    image: registry:5000/tradr-all-stocks-stage-classifier
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-all-stocks-stage-classifier"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
    environment:
      - SA_ITERATION=1
      - SA_WAKEUP_HOUR=2
      - SA_WATCHLIST=C,CALM,CAT,F,H,HLT,IRTC,JPM,TSLA,UBER
      - SA_ALERTS_EMAIL_LIST=richard.crouch100@gmail.com
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
