#!/bin/bash -eu
echo ' '
echo 'TRADR help'
echo '----------'
echo 'upgrade           : Upgrade TRADR (Docker applications) to the latest version'
echo 'cli               : Start the TRADR command-line (for admin and user commands)'
echo 'run_tradr_daemons : Start the TRADR scanner(s)'
echo 'install_tradr     : First time installation of TRADR'
echo 'help              : Display this page'
echo 'version_tradr     : Display version information'
echo 'backup            : Backup TRADR MySQL database to host'
echo 'restore           : Restore TRADR MySQL database from host backup'
echo ' '
