#!/bin/bash -eu
echo ' '
echo 'TRADR help'
echo '----------'
echo 'upgrade   : Upgrade TRADR to the latest version'
echo 'cli       : Start the TRADR command-line (for admin and user commands)'
echo 'run_tradr : Start the TRADR scanner(s)'
echo 'help      : Display this page'
echo 'version   : Display version information'
echo 'backup    : Backup MySQL database'
echo 'restore   : Restore MySQL database from backup'
echo ' '
