# This runs on the Docker Host

version: '3'

services:
  namecheap-updater:
    container_name: namecheap-updater
    image: registry:5000/namecheap-updater
    logging:
      driver: syslog
      options:
        tag: "namecheap-updater"
    environment:
      NAMECHEAP_DNS_PASSWORD: 369897823b7640a5838f1d2d746121dc
      NAMECHEAP_DNS_UPDATE_MINUTES: 15
