version: '3'

services:
  tradr-parse-patternz-trades-file:
    container_name: tradr-parse-patternz-trades-file
    image: registry:5000/tradr-parse-patternz-trades-file
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-parse-patternz-trades-file"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./reports:/reports
      - ./yahoo_fin_historical_data:/yahoo_fin_historical_data
    environment:
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - CHATGPT_API_KEY=${CHATGPT_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
