version: '3'

# Run REST services first
services:

  buy_sniper_0:
    container_name: tradr-rsi-buy-sniper-0
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=0
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_1:
    container_name: tradr-rsi-buy-sniper-1
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=1
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_2:
    container_name: tradr-rsi-buy-sniper-2
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=2
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_3:
    container_name: tradr-rsi-buy-sniper-3
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=3
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_4:
    container_name: tradr-rsi-buy-sniper-4
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=4
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_5:
    container_name: tradr-rsi-buy-sniper-5
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=5
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_6:
    container_name: tradr-rsi-buy-sniper-6
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=6
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_7:
    container_name: tradr-rsi-buy-sniper-7
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=7
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_8:
    container_name: tradr-rsi-buy-sniper-8
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=8
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_9:
    container_name: tradr-rsi-buy-sniper-9
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=9
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_10:
    container_name: tradr-rsi-buy-sniper-10
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=10
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_11:
    container_name: tradr-rsi-buy-sniper-11
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=11
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_12:
    container_name: tradr-rsi-buy-sniper-12
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=12
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_13:
    container_name: tradr-rsi-buy-sniper-13
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=13
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_14:
    container_name: tradr-rsi-buy-sniper-14
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=14
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  buy_sniper_15:
    container_name: tradr-rsi-buy-sniper-15
    image: registry:5000/tradr-rsi-buy-sniper
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-rsi-buy-sniper"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
      - ./keys:/app/keys
    environment:
      - INSTANCE=15
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
