version: '3'

services:
  tradr-stage-change-alerter:
    container_name: tradr-stage-change-alerter
    image: registry:5000/tradr-stage-change-alerter
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-stage-change-alerter"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
    environment:
      - STAGE_CHANGE_ITERATION=2
      - STAGE_CHANGE_REPORT_HOUR=3
      - SA_WATCHLIST=C,CALM,CAT,F,H,HLT,IRTC,JPM,TSLA,UBER
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
