version: '3'

# Run REST services first
services:
  tradr_exchange_rate_service:
    container_name: tradr-exchange-rate-service
    image: registry:5000/tradr-exchange-rate-service
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-exchange-rate-service"
    network_mode: "host"

#  indices_grabber:
#    container_name: tradr-indices-grabber
#    image: registry:5000/tradr-indices-grabber
#    logging:
#      driver: "syslog"
#      options:
#        syslog-address: "udp://127.0.0.1:514"
#        tag: "tradr-indices-grabber"
#    network_mode: "host"
#    volumes:
#      - /var/lib/mysql/mysql.sock:/mysql.sock
#    environment:
#      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
#      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
#      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
#      - VONAGE_API_KEY=${VONAGE_API_KEY}
#      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
#      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
#      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
#      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
#
#  bitcoin_grabber:
#    container_name: tradr-bitcoin-grabber
#    image: registry:5000/tradr-bitcoin-grabber
#    logging:
#      driver: "syslog"
#      options:
#        syslog-address: "udp://127.0.0.1:514"
#        tag: "tradr-bitcoin-grabber"
#    network_mode: "host"
#    volumes:
#      - /var/lib/mysql/mysql.sock:/mysql.sock
#    environment:
#      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
#      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
#      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
#      - VONAGE_API_KEY=${VONAGE_API_KEY}
#      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
#      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
#      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
#      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
#
#  ibit_grabber:
#    container_name: tradr-ibit-grabber
#    image: registry:5000/tradr-ibit-grabber
#    logging:
#      driver: "syslog"
#      options:
#        syslog-address: "udp://127.0.0.1:514"
#        tag: "tradr-ibit-grabber"
#    network_mode: "host"
#    volumes:
#      - /var/lib/mysql/mysql.sock:/mysql.sock
#    environment:
#      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
#      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
#      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
#      - VONAGE_API_KEY=${VONAGE_API_KEY}
#      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
#      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
#      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
#      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
#
#  commodities_grabber:
#    container_name: tradr-commodities-grabber
#    image: registry:5000/tradr-commodities-grabber
#    logging:
#      driver: "syslog"
#      options:
#        syslog-address: "udp://127.0.0.1:514"
#        tag: "tradr-commodities-grabber"
#    network_mode: "host"
#    volumes:
#      - /var/lib/mysql/mysql.sock:/mysql.sock
#    environment:
#      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
#      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
#      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
#      - VONAGE_API_KEY=${VONAGE_API_KEY}
#      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
#      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
#      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
#      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
#
#  treasuries_grabber:
#    container_name: tradr-treasuries-grabber
#    image: registry:5000/tradr-treasuries-grabber
#    logging:
#      driver: "syslog"
#      options:
#        syslog-address: "udp://127.0.0.1:514"
#        tag: "tradr-treasuries-grabber"
#    network_mode: "host"
#    volumes:
#      - /var/lib/mysql/mysql.sock:/mysql.sock
#    environment:
#      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
#      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
#      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
#      - VONAGE_API_KEY=${VONAGE_API_KEY}
#      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
#      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
#      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
#      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
#
#  tepper_indicators:
#    container_name: tradr-tepper-indicators
#    image: registry:5000/tradr-tepper-indicators
#    logging:
#      driver: "syslog"
#      options:
#        syslog-address: "udp://127.0.0.1:514"
#        tag: "tradr-tepper-indicators"
#    network_mode: "host"
#    volumes:
#      - /var/lib/mysql/mysql.sock:/mysql.sock
#    environment:
#      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
#      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
#      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
#      - VONAGE_API_KEY=${VONAGE_API_KEY}
#      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
#      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
#      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
#      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
#
#  core_ratios:
#    container_name: tradr-core-ratios
#    image: registry:5000/tradr-core-ratios
#    logging:
#      driver: "syslog"
#      options:
#        syslog-address: "udp://127.0.0.1:514"
#        tag: "tradr-core-ratios"
#    network_mode: "host"
#    volumes:
#      - /var/lib/mysql/mysql.sock:/mysql.sock
#    environment:
#      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
#      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
#      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
#      - VONAGE_API_KEY=${VONAGE_API_KEY}
#      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
#      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
#      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
#      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
#
#  swing_trader:
#    container_name: tradr-scanner
#    image: registry:5000/tradr-scanner
#    privileged: true
#    logging:
#      driver: "syslog"
#      options:
#        syslog-address: "udp://127.0.0.1:514"
#        tag: "tradr-scanner"
#    network_mode: "host"
#    volumes:
#      - /var/lib/mysql/mysql.sock:/mysql.sock
#    devices:
#      - /dev/snd:/dev/snd
#    environment:
#      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
#      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
#      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
#      - VONAGE_API_KEY=${VONAGE_API_KEY}
#      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
#      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
#      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
#      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
#
#  assets_tracker:
#    container_name: tradr-assets-tracker
#    image: registry:5000/tradr-assets-tracker
#    logging:
#      driver: "syslog"
#      options:
#        syslog-address: "udp://127.0.0.1:514"
#        tag: "tradr-assets-tracker"
#    network_mode: "host"
#    volumes:
#      - /var/lib/mysql/mysql.sock:/mysql.sock
#    environment:
#      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
#      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
#      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
#      - VONAGE_API_KEY=${VONAGE_API_KEY}
#      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
#      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
#      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
#      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
#
  tradr-all-stocks-stage-classifier:
    container_name: tradr-all-stocks-stage-classifier
    image: registry:5000/tradr-all-stocks-stage-classifier
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-all-stocks-stage-classifier"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
    environment:
      - SA_ITERATION=2
      - SA_WAKEUP_HOUR=10
      - SA_ADHOC_WATCHLIST=ADBE,AI,ALAR,APG,AU,AXON,CARG,CCJ,CDE,CDNA,CFLT,CHKP,CNK,CRDO,CYBR,ESTC,HACK,HMY,MSTR,PLTR,RIVN,RPAY,VRNS,ZS
      - SA_ALERTS_EMAIL_LIST=richard.crouch100@gmail.com
      - SA_SCAN_FTSE=True
      - SA_SCAN_SP500=False
      - SA_SCAN_NASDAQ=False
      - SA_VOLUME_K_FACTOR=1.701
      - SA_MRP_MIN_THRESHOLD=1.01
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  tradr-stage-change-alerter:
    container_name: tradr-stage-change-alerter
    image: registry:5000/tradr-stage-change-alerter
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-stage-change-alerter"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
    environment:
      - STAGE_CHANGE_ITERATION=2
      - STAGE_CHANGE_REPORT_HOUR=11
      - STAGE_CHANGE_WATCHLIST=ADBE,AI,ALAR,APG,AU,AXON,CARG,CCJ,CDE,CDNA,CFLT,CHKP,CNK,CRDO,CYBR,ESTC,HACK,HMY,MSTR,PLTR,RIVN,RPAY,VRNS,ZS
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
