# -*- mode: ruby -*-
# vi: set ft=ruby :

# STAGING (xw6600) in Ermin setup

# smarter way to do multi-machine is here : https://manski.net/articles/vagrant/multi-machine-tutorial

Vagrant.configure("2") do |config|

  # Services VBOX
  # =============
  # Start first as it is the logging server node
  config.vm.define "itg_services" do |itg_services|
    itg_services.vm.box = "tradr7-services"
    itg_services.vm.hostname = "itg-services"
    itg_services.vm.network :public_network, ip: "192.168.1.51", bridge: "eth0"

    itg_services.vm.provider "virtualbox" do |vb0|
        vb0.gui = true
        vb0.memory = "3072"
    end
    itg_services.vm.provision "file", source: "../common_scripts/disable_firewall_patch.sh", destination: "disable_firewall_patch.sh"
    itg_services.vm.provision "file", source: "../common_scripts/start_elasticsearch_patch.sh", destination: "start_elasticsearch_patch.sh"
    itg_services.vm.provision "file", source: "../common_scripts/start_filebeat_patch.sh", destination: "start_filebeat_patch.sh"
    itg_services.vm.provision "shell", run:  "always", inline: "ip route del 0/0"
    itg_services.vm.provision "shell", run:  "always", inline: "route add default gw 192.168.1.1"
    # itg_services.vm.provision "shell", run:  "always", inline: "route add default gw 192.168.1.254"
    itg_services.vm.provision "shell", path:  "../common_scripts/disable_firewall_patch.sh"
    itg_services.vm.provision "shell", path:  "../common_scripts/start_elasticsearch_patch.sh"
    itg_services.vm.provision "shell", path:  "../common_scripts/start_filebeat_patch.sh"
    itg_services.vm.provision "shell", path:  "../common_scripts/clean_up.sh"
  end       # of itg_services

  # Application VBOX
  # ================
  # All my TRADR application code is on here - node subject to lots of change
  # This is the node the user interacts with - the 'iceberg' terminal
  # Docker, Jython etc.
  config.vm.define "itg_iceberg" do |iceberg|
    iceberg.vm.box = "tradr7"
  #  # tradr0.vm.box_check_update = true
    iceberg.vm.hostname = "itg-iceberg"
    iceberg.vm.network :public_network, ip: "192.168.1.50", bridge: "eth0"
    iceberg.vm.provider "virtualbox" do |vb0|
        vb0.gui = true
        vb0.memory = "4096"
    end
      iceberg.vm.provision "file", source: "../common_scripts/configure.sh", destination: "configure.sh"
      iceberg.vm.provision "file", source: "../common_scripts/clean_up.sh", destination: "clean_up.sh"
      iceberg.vm.provision "file", source: "../common_scripts/start_stocks_scanner.sh", destination: "start_stocks_scanner.sh"
      iceberg.vm.provision "file", source: "../common_scripts/disable_firewall_patch.sh", destination: "disable_firewall_patch.sh"
      iceberg.vm.provision "shell", path:  "../common_scripts/disable_firewall_patch.sh"
      iceberg.vm.provision "shell", run:  "always", inline: "ip route del 0/0"
      iceberg.vm.provision "shell", run:  "always", inline: "route add default gw 192.168.1.1"
      iceberg.vm.provision "shell", env: {
                                        'SQL_DB_HOSTNAME' => '127.0.0.1',
                                        'VONAGE_API_SECRET' => ENV['VONAGE_API_SECRET'],
                                        'VONAGE_API_KEY' => ENV['VONAGE_API_KEY'],
                                        'FMP_FREE_API_KEY' => ENV[ 'FMP_FREE_API_KEY'],
                                        'PROTONMAIL_PLUS_BRIDGE_KEY' => ENV['PROTONMAIL_PLUS_BRIDGE_KEY'],
                                        'ALPHAVANTAGE_BASIC_API_KEY' => ENV['ALPHAVANTAGE_BASIC_API_KEY'],
                                        'ALPHAVANTAGE_FREE_API_KEY' => ENV['ALPHAVANTAGE_FREE_API_KEY']
                                         },
                                         path: '../common_scripts/setup_env_vars.sh'
    iceberg.vm.provision "shell", path:  "../common_scripts/set_symlinks.sh"
    iceberg.vm.provision "shell", path:  "../common_scripts/clean_up.sh"
  end       # of iceberg

end
