{
 "title": "Iceberg",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Number of Stocks",
   "type": "stat",
   "description": "Number of stocks in initial purchase",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  initial_position_num_stocks\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Purchase Price (USD)",
   "type": "stat",
   "description": "initial_purchase_price_usd",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  initial_position_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Current Price (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  stock_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Profit (GBP)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  profit_gbp\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Profit (Ignore slippage) USD",
   "type": "stat",
   "description": "Profit per share x number of shares",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  profit_ignore_slippage_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total Risk (USD)",
   "type": "stat",
   "description": "Risk per share x number of shares",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  total_risk_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Price (USD)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  stock_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Profit (GBP)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  profit_gbp\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Risk:Reward Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  risk_reward_ratio\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  initial_position_risk_reward_ratio\nFROM iceberg\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Peak Current Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  peak_current_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Peak Profit (GBP)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  peak_profit_gbp\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Initial Stop Loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  initial_stop_loss_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Sell Stop",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sell_stop_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Take Profit (USD)",
   "type": "stat",
   "description": "Based on risk:reward ration of approx 1:3",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  take_profit_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Exit Trade (Stop)",
   "type": "stat",
   "description": "Sell if share price exceeds this value",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  exit_trade_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Buy The Dip (Stop)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  buy_the_dip_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Buy Time Slippage (GBP)",
   "type": "stat",
   "description": "What were the costs to buy the shares ?",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  buytime_slippage_gbp\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "MA Signal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  ma_signal\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "SP 500",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price\nFROM iceberg_sp500\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price_usd\nFROM iceberg_bitcoin\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (change %)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  change_percent\nFROM iceberg_bitcoin\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (GBP)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price_gbp\nFROM iceberg_bitcoin\nORDER BY time"
    }
   ]
  },
  {
   "title": "IBIT (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price_usd\nFROM iceberg_ibit\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Trade (volume)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  volume_sma\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Auto-Trailing Stop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  trailing_stop_usd\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  stock_price_usd\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  peak_current_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Trade Profit (GBP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  profit_gbp\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  peak_profit_sma_gbp\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "SP500 (Detailed)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price\nFROM iceberg_sp500\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma200\nFROM iceberg_sp500\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma50\nFROM iceberg_sp500\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  year_high\nFROM iceberg_sp500\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  year_low\nFROM iceberg_sp500\nORDER BY time"
    }
   ]
  },
  {
   "title": "Exchange Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  exchange_rate\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "MA Signal",
   "type": "graph",
   "description": "Moving Average Signal. 2=BUY, 4 = SELL, 0 = DO NOTHING.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  ma_signal\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "MA monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma20_usd\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma50_usd\nFROM iceberg\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma150_usd\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  stock_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (volume)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  volume\nFROM iceberg_bitcoin\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (price)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price_usd\nFROM iceberg_bitcoin\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price_gbp\nFROM iceberg_bitcoin\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma200\nFROM iceberg_bitcoin\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma50\nFROM iceberg_bitcoin\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  year_high\nFROM iceberg_bitcoin\nORDER BY time"
    }
   ]
  }
 ]
}