{
 "title": "SwingTrading",
 "description": "Trades on 3-5 day timescale",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Silver Miners Latest Priice (USD)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  silver_miners_latest_price_usd\nFROM iceberg_core_ratios\nORDER BY time"
    }
   ]
  },
  {
   "title": "Profit (GBP)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  profit_gbp\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Profit (Ignore slippage) USD",
   "type": "stat",
   "description": "Profit per share x number of shares",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  profit_ignore_slippage_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total Risk (USD)",
   "type": "stat",
   "description": "Risk per share x number of shares",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  total_risk_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Risk:Reward Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  risk_reward_ratio\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  initial_position_risk_reward_ratio\nFROM iceberg\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Gold Miners (GDX) Price (USD)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  gold_miners_latest_price_usd\nFROM iceberg_core_ratios\nORDER BY time"
    }
   ]
  },
  {
   "title": "Buy The Dip (Stop)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  buy_the_dip_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Buy Time Slippage (GBP)",
   "type": "stat",
   "description": "What were the costs to buy the shares ?",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  buytime_slippage_gbp\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (change %)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  change_percent\nFROM iceberg_bitcoin\nORDER BY time"
    }
   ]
  },
  {
   "title": "IBIT (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price_usd\nFROM iceberg_ibit\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Silver:Satoshis (Bitcoin) Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  silver_sats_ratio\nFROM iceberg_core_ratios\nORDER BY time"
    }
   ]
  },
  {
   "title": "Gold:Satoshis (Bitcoin) Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  gold_sats_ratio\nFROM iceberg_core_ratios\nORDER BY time"
    }
   ]
  },
  {
   "title": "Gold:Silver Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  gold_silver_ratio\nFROM iceberg_core_ratios\nORDER BY time"
    }
   ]
  },
  {
   "title": "Gold:Gold Miners Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  gold_gold_miners_ratio\nFROM iceberg_core_ratios\nORDER BY time"
    }
   ]
  },
  {
   "title": "Heating Oil Futures ($)",
   "type": "timeseries",
   "description": "HOUSD",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_hgusd\nORDER BY time"
    }
   ]
  },
  {
   "title": "Gasoline Futures ($)",
   "type": "timeseries",
   "description": "RBUSD",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_rbusd\nORDER BY time"
    }
   ]
  },
  {
   "title": "Platinum Futures ($)",
   "type": "timeseries",
   "description": "PLUSD",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_plusd\nORDER BY time"
    }
   ]
  },
  {
   "title": "Natural Gas Futures ($)",
   "type": "timeseries",
   "description": "NGUSD",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_ngusd\nORDER BY time"
    }
   ]
  },
  {
   "title": "Silver Futures ($)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_siusd\nORDER BY time"
    }
   ]
  },
  {
   "title": "Copper Futures",
   "type": "timeseries",
   "description": "This makes copper prices a good leading indicator of the economic cycle.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_hgusd\nORDER BY time"
    }
   ]
  },
  {
   "title": "Crude Oil Futures (CLUSD)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_clusd\nORDER BY time"
    }
   ]
  },
  {
   "title": "Brent Crude ($)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_bzusd\nORDER BY time"
    }
   ]
  },
  {
   "title": "Number of Stocks",
   "type": "stat",
   "description": "Number of stocks in initial purchase",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  initial_position_num_stocks\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Purchase Price (USD)",
   "type": "stat",
   "description": "initial_purchase_price_usd",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  initial_position_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Current Price (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  stock_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Price (USD)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  stock_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Profit (GBP)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  profit_gbp\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Peak Current Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 123 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  peak_current_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Peak Profit (GBP)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 123 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  peak_profit_gbp\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Initial Stop Loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 123 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  initial_stop_loss_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Sell Stop",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 123 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sell_stop_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Take Profit (USD)",
   "type": "stat",
   "description": "Based on risk:reward ration of approx 1:3",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 123 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  take_profit_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Exit Trade (Stop)",
   "type": "stat",
   "description": "Sell if share price exceeds this value",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 123 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  exit_trade_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "MA Signal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 127 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  ma_signal\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "SP 500",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 127 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_gspc\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 127 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price_usd\nFROM iceberg_bitcoin\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (GBP)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 127 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price_gbp\nFROM iceberg_bitcoin\nORDER BY time"
    }
   ]
  },
  {
   "title": "Trade (volume)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  volume_sma\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Auto-Trailing Stop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  trailing_stop_usd\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  stock_price_usd\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  peak_current_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Trade Profit (GBP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  profit_gbp\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  peak_profit_sma_gbp\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (volume)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  volume\nFROM iceberg_bitcoin\nORDER BY time"
    }
   ]
  },
  {
   "title": "Exchange Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 139 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  exchange_rate\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "MA Signal",
   "type": "graph",
   "description": "Moving Average Signal. 2=BUY, 4 = SELL, 0 = DO NOTHING.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  ma_signal\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "MA monitor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma20_usd\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma50_usd\nFROM iceberg\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma150_usd\nFROM iceberg\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  stock_price_usd\nFROM iceberg\nORDER BY time"
    }
   ]
  },
  {
   "title": "SP500",
   "type": "graph",
   "description": "GSPC",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_gspc\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma200\nFROM iceberg_gspc\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma50\nFROM iceberg_gspc\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (price)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price_usd\nFROM iceberg_bitcoin\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  price_gbp\nFROM iceberg_bitcoin\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma200\nFROM iceberg_bitcoin\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  sma50\nFROM iceberg_bitcoin\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  year_high\nFROM iceberg_bitcoin\nORDER BY time"
    }
   ]
  },
  {
   "title": "FTSE100",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_ftse\nORDER BY time"
    }
   ]
  },
  {
   "title": "NASDAQ",
   "type": "timeseries",
   "description": "IXIC",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_ixic\nORDER BY time"
    }
   ]
  },
  {
   "title": "GCUSD - Gold Futures ($)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_gcusd\nORDER BY time"
    }
   ]
  },
  {
   "title": "US Dollar DXY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_dxynyb\nORDER BY time"
    }
   ]
  },
  {
   "title": "CBOE Volatility (VIX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value\nFROM iceberg_vix\nORDER BY time"
    }
   ]
  },
  {
   "title": "US Treasury",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  thirteen_week\nFROM iceberg_yield_curve\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  five_year\nFROM iceberg_yield_curve\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  ten_year\nFROM iceberg_yield_curve\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  thirty_year\nFROM iceberg_yield_curve\nORDER BY time"
    }
   ]
  }
 ]
}