version: '3'

# Run REST services first
services:
  tradr_exchange_rate_service:
    container_name: tradr-exchange-rate-service
    image: registry:5000/tradr-exchange-rate-service
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-exchange-rate-service"
    network_mode: "host"

  tradr-all-stocks-stage-classifier:
    container_name: tradr-all-stocks-stage-classifier
    image: registry:5000/tradr-all-stocks-stage-classifier
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-all-stocks-stage-classifier"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
    environment:
      - SA_ITERATION=2
      - SA_WAKEUP_HOUR=10
      - SA_ADHOC_WATCHLIST=ADBE,AI,ALAR,APG,AU,AXON,CARG,CCJ,CDE,CDNA,CFLT,CHKP,CNK,CRDO,CYBR,ESTC,HACK,HMY,MSTR,PLTR,RIVN,RPAY,VRNS,ZS
      - SA_ALERTS_EMAIL_LIST=richard.crouch100@gmail.com
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  tradr-stage-change-alerter:
    container_name: tradr-stage-change-alerter
    image: registry:5000/tradr-stage-change-alerter
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-stage-change-alerter"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
    environment:
      - STAGE_CHANGE_ITERATION=2
      - STAGE_CHANGE_REPORT_HOUR=11
      - STAGE_CHANGE_WATCHLIST=ADBE,AI,ALAR,APG,AU,AXON,CARG,CCJ,CDE,CDNA,CFLT,CHKP,CNK,CRDO,CYBR,ESTC,HACK,HMY,MSTR,PLTR,RIVN,RPAY,VRNS,ZS
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'
