version: '3'

# Run REST services first
services:
  tradr_exchange_rate_service:
    container_name: tradr-exchange-rate-service
    image: registry:5000/tradr-exchange-rate-service
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-exchange-rate-service"
    network_mode: "host"

  tradr-all-stocks-stage-classifier:
    container_name: tradr-all-stocks-stage-classifier
    image: registry:5000/tradr-all-stocks-stage-classifier
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-all-stocks-stage-classifier"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
    environment:
      - SA_ITERATION=2
      - SA_WAKEUP_HOUR=2
      - SA_ADHOC_WATCHLIST=AAPL,ALTR,COHR,COLM,CORZ,CVNA,GEN,HIMS,HPQ,IFF,INTU,KGC,LZB,MMM,MNDY,MSFT,NET,SPOT,XBI
      - SA_ALERTS_EMAIL_LIST=richard.crouch100@gmail.com
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'

  tradr-daily-report:
    container_name: tradr-daily-report
    image: registry:5000/tradr-daily-report
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://127.0.0.1:514"
        tag: "tradr-daily-report"
    network_mode: "host"
    volumes:
      - /var/lib/mysql/mysql.sock:/mysql.sock
    environment:
      - DAILY_REPORT_ITERATION=2
      - DAILY_REPORT_HOUR=9
      - DAILY_REPORT_EMAIL_LIST=richard.crouch100@gmail.com
      - DAILY_REPORT_ADHOC_WATCHLIST=AAPL,ALTR,COHR,COLM,CORZ,CVNA,GEN,HIMS,HPQ,IFF,INTU,KGC,LZB,MMM,MNDY,MSFT,NET,SPOT,XBI
      - SQL_DB_HOSTNAME=${SQL_DB_HOSTNAME}
      - FMP_FREE_API_KEY=${FMP_FREE_API_KEY}
      - VONAGE_API_SECRET=${VONAGE_API_SECRET}
      - VONAGE_API_KEY=${VONAGE_API_KEY}
      - PROTONMAIL_PLUS_BRIDGE_HOSTNAME=${PROTONMAIL_PLUS_BRIDGE_HOSTNAME}
      - PROTONMAIL_PLUS_BRIDGE_PORT=${PROTONMAIL_PLUS_BRIDGE_PORT}
      - PROTONMAIL_PLUS_BRIDGE_KEY=${PROTONMAIL_PLUS_BRIDGE_KEY}
      - ALPHAVANTAGE_BASIC_API_KEY=${ALPHAVANTAGE_BASIC_API_KEY}
      - ALPHAVANTAGE_FREE_API_KEY=${ALPHAVANTAGE_FREE_API_KEY}
      - YAHOO_FREE_API_KEY='NONE_REQUIRED'